### ISSUE TITLE
ORing flags together

### ISSUE THREAD

**Issue by WillLuce** [akheron/jansson#219]
Can someone give me an example of ORing flags together? I'm trying to use JSON_INDENT and JSON_REAL_PRECISION, but I don't have a clue what it meant by ORing something. Thanks ahead of time.

**Comment by akheron** [comment]
`JSON_INDENT(4) | JSON_REAL_PRECISION(2)`

**Comment by WillLuce** [comment]
Thanks for this, but it doesn’t seem to work. It seems that JSON_REAL_PRECISION(n) isn’t an option.

Here’s my line of c++, but I’m getting an error on the precision.

int buildFile = json_dump_file(root, outFile, JSON_INDENT(3) | JSON_REAL_PRECISION(4));

Thanks.

**Comment by akheron** [comment]
`JSON_REAL_PRECISION` is a new feature in Jansson 2.7. You need to update if you're using an older version.

**Comment by ljjimenez** [comment]
Hello I have jansson 2.7, but JSON_REAL_PRECISION doesn't work for me.

**Comment by akheron** [comment]
How does it not work? Could you be more specific?

**Comment by WillLuce** [comment]
Someone got with me on this problem and solved it. I’m not sure why they didn’t mark it as solved. I do have another problem out there about not writing to file. I’ve posted it in the last 3 days and had no response.

**Comment by ljjimenez** [comment]
Because this is my source:

#include <stdio.h>

#include <jansson.h>

#include <locale.h>


int main(int argc, char **argv)

{

setlocale(LC_ALL, "en_US.utf8");


 json_t *root;

root = json_object();


 json_object_set_new(root, "price", json_real((double)256.390));


 printf("\n\n");


 size_t flags = JSON_INDENT(2)|JSON_PRESERVE_ORDER|JSON_REAL_PRECISION(2);


 json_dumpf(root, stdout, flags);

printf("\n\n");


 printf("VERSION: %s\n", JANSSON_VERSION);


 json_decref(root);


 return 0;

}


And this is the output:



{

  "price": 256.38999999999999

}


VERSION: 2.7


 But should be as i understand:



{

  "price": 256.39

}


VERSION: 2.7

**Comment by akheron** [comment]
For me, the output is as follows:
```
{
  "price": 2.6e2
}

VERSION: 2.7
```

Though `2.6e2` is probably not always what is wanted... But the number is truncated anyway.

**Comment by ljjimenez** [comment]
Ok, what should i do if i want money presentation?

**Comment by akheron** [comment]
Well, the first problem is that `JSON_REAL_PRECISION` seems not to be working for you at all, which is weird. What does the following code print:

```c
printf("%.3g\n", 1.23456)
```

It should print `1.23`, but if it doesn't, there's something wrong in your environment.

What comes to money representation, it's not possible to do currently. I guess it would be hard on other JSON implementations, too. Your best choice is to use strings to represent fixed precisiong decimals.

**Comment by ljjimenez** [comment]
It does, it prints 1.23

1.23

**Comment by akheron** [comment]
What about `snprintf()`, does it work too? That's what Jansson users internally.

**Comment by ljjimenez** [comment]
snprintf works fine too.

VERSION: 2.7

using printf:   1.23

using snprintf: 1.23

**Comment by akheron** [comment]
In this case, the only thing I can think of is that your jansson.h is from version 2.7 but the library (.so, .dll, .dylib, whatever) is from an older version. `JANSSON_VERSION` is defined in the header but all the actual code is in the library file.

If you're on Linux, the library filename is libjansson.so.4.7.0 for Jansson 2.7 and libjansson.so.4.6.0 for Jansson 2.6.

**Comment by GuillaumeLeclerc** [comment]
I do have the same problem as described here.

**Comment by cyberrbob** [comment]
The problem is with '"%.*g" formatter in jsonp_dtostr. See how it works:
`printf("\nval1: %.*g \n", 2, 12.3456789); // will produce val1: 12`

but we actually want 12.34
`printf("\nval1: %.*f \n", 2, 12.3456789); // will produce val1: 12.34`

Conforming doc's %g must use the shorted representation of %e or %f, but seems it just drops given value to specified number of valued chars. 
another example:
printf("\nval1: %.*g \n", 2, 12345.6789); // will produce val1: 1.2e+04

We use your library in our project but unfortunately can't use JSON_REAL_PRECISION feature because of this behavior :(

**Comment by wagnerjs** [comment]
I have the same problem described by @cyberrbob.

I would like to understand why the current behavior is the expected behavior to setting precision of real numbers once we are loosing representative values in decimal fraction (as in example above).

**Comment by akheron** [comment]
`JSON_REAL_PRECISION` was added a long time ago, so I don't remember the details very well.

The default precision is 17, because `"%.17g"` is enough to represent all doubles. The reason `JSON_REAL_PRECISION(n)` uses `"%.*g", n` is probably an oversight, as it prints `n` *significant* digits. It should probably have been `"%.*f", n` to print `n` digits after the decimal point.

However, the problem with `%.*f` is that it prints all the digits after the decimal point, even if they're all zero. So you would get numbers like `123.00` in the output.
