### ISSUE TITLE
Feature request: Expose the hashtable serial for order preserved iteration

### ISSUE THREAD

**Issue by Tigzy** [akheron/jansson#245]
Hello, 
Currently my "GetKeys" iteration function looks like this, and returns randomly ordered keys: 

```
vector<wstring> JsonDB::GetKeys( json_t* rootVal )
{    
    vector<wstring> vec;
    const char *key = NULL;
    json_t* value   = NULL;

    if ( !json_is_object( rootVal ) )
        return vec;

    json_object_foreach( rootVal, key, value )
        vec.push_back( mstring::from_string(key) );

    return vec;
}
```

It would be a good idea for one that wants to keep the original hash order to expose the hashtable_pair.serial field with an API, or within an existing iteration API. 
My current workaround is a bit hacky because it redefines some existing internal functions and structures to wrap it into a C++ layer: 

```
vector<string> JsonDB::GetKeysPreserveOrder( json_t* rootVal )
{    
    if ( !json_is_object( rootVal ) )
        return vector<string>();

    size_t size = json_object_size( rootVal );
    if ( !size ) return vector<string>();

    vector<string> vec( size );

    void* iter = json_object_iter( rootVal );
    while(iter)
    {
        size_t serial       = hashtable_iter_serial(iter);
        vec.at( serial )   = json_object_iter_key( iter );
        iter              = json_object_iter_next( rootVal, iter );
    }
    return vec;
}
```

My question is: Maybe json_object_iter_key could expose the serial as well?

**Comment by akheron** [comment]
(Side note: the serial numbers are not necessarily continuous if key-value pairs have been deleted from the object at some point. So having a fixed-size vector and indexing it with the serial number does not work in the general case.)

Exposing the serial number could be done. But I'd also like to provide some kind of helper to iterate the key-value pairs of an object in insertion order because that's the most common use case. I just haven't come up with a good API, and am very much welcome to suggestions. Because of the note above, the process involves sorting in the general case and thus requires temporary storage. So I don't see how a simple macro could be enough.

**Comment by dtikhonov** [comment]
@akheron, one way to do it is to keep all items on a master list.  This costs two pointers per hash element, but it is simple to implement and no temporary storage is required.

The iterator could be built into `json_object_t` itself:

```c
/* Resets iterator to first element.  Returns NULL if object has no elements. */
json_t *
json_object_first_el(json_t *, const char **key /* optional */);

/* Returns next element or NULL when it runs out. */
json_t *
json_object_next_el(json_t *, const char **key /* optional */);
```
