### ISSUE TITLE
clarification on memory management

### ISSUE THREAD

**Issue by phatmanace** [akheron/jansson#277]
Folks, 

I'm hoping someone can help me a little with how to clean up jansson objects that are no-longer needed. Currently, I'm doing something like (cribbing from the example provided in the docs tutorial)

```
root = json_loads(s.ptr, 0, &error);
			if(!root){
				printf("Parsing failed...  ");
				printf("Text was |%s|\n", s.ptr);
			}
			id = json_object_get(root, "id");
			jtx = json_object_get(root, "text");
```
Then later, after doing things with `id` and `jtx`... 

 ```
                       
json_decref(id);
json_decref(jtx);
 json_decref(root);
```

is this the correct way to deallocate the memory? - it seems to be causing some odd memory corruption problems with other (non-jansson related) bits of my program - so I suspect I'm doing something incorrect.

For example, should I only call `decref` on the root and just use `free()` on the others?

If there examples in the docs, or small repro, I'd be most grateful.

Thanks, Ace

**Comment by akheron** [comment]
You only need to decref root, and leave the others alone. In your example, json_loads returns a **new reference**, something that you own and need to decref to free the memory. On the contrary, json_object_get returns a **borrowed reference**, so you don't own the value, just borrow it, so you don't need to do anything to free it.

**Comment by akheron** [comment]
Here's a link to the reference count section in the documentation: https://jansson.readthedocs.org/en/2.7/apiref.html#reference-count

**Comment by phatmanace** [comment]
Thanks, I went back and re-read the docs and it still wasn't very obvious to me - but your post above helps enormously - thanks very much!

**Comment by JDetwiler15** [comment]
While borrowed references are explained in the documentation, I agree that it's very not obvious that you only `json_decref` the root object. For example, it's explained that the user "must call `json_incref`" only to say that "normally...functions...manage the reference". Is this to say that sometimes the function won't manage the reference? Do I still need to call `json_incref`? 

This documentation is lacking in meaningful examples for freeing memory; I spent an hour just now debugging, searching, and reading when this issue here immediately solved my problem. I feel like this issue should be reopened solely for the documentation to be improved in this area.
