### ISSUE TITLE
Parsing JSON is a Minefield

### ISSUE THREAD

**Issue by benrubson** [akheron/jansson#331]
Hello,

What about trying to solve parsing issues Nicolas revealed in his article ?
http://seriot.ch/parsing_json.php
This would make Jansson even better.

Many thanks 👍 

Ben

**Comment by akheron** [comment]
An interesting comparison, I hadn't seen it before. Thanks for pointing it out.

What comes to Jansson's results, it seems to me that `n_multidigit_number_then_00.json` is the only one that needs fixing.

Regarding `y_object_escaped_null_in_key.json`, both RFC 7159 and RFC 4627 (which was the current spec when Jansson was initially written), allow limiting character contents of strings. Jansson initially disallowed the NUL byte completely, but has since added support for NUL byte in string values. Support for object keys would bloat the API, and I don't remember ever receiving a feature request for supporting NUL bytes in object keys.

**Comment by benrubson** [comment]
Thank you for your feedback !

Yes sounds like `n_multidigit_number_then_00.json` could be corrected.

Regarding `y_object_escaped_null_in_key.json`, what is Jansson behaviour in this case ? Does it stop when it encounters this "strange" key ? Or does it continue up to the end of the json string (simply ignoring keys with NUL bytes) ?

Regarding light blue / dark blue tests, I'm not sure what it the best behaviour, as in both cases result is undefined I think we don't mind, but perhaps @nst could tell us.

The comparison also points that Jansson rejects big numbers, but sounds like @sakubara [is working on a solution](https://github.com/akheron/jansson/issues/69).
