### ISSUE TITLE
json_error_t to contain error type

### ISSUE THREAD

**Issue by veselov** [akheron/jansson#352]
It would be really useful is json_error_t had a value that was useful to programmatically determining the problem with parsing. Specifically, if the problem is related to the input (syntax), or, say, memory shortage.

**Comment by t-kin** [comment]
Input syntax

**Comment by akheron** [comment]
Unfortunately, due to `json_error_t` being allocated on the stack, fields cannot be added to it without breaking ABI compatibility. IMO, such a small change on its own doesn't warrant such a breakage.

**Comment by phst** [comment]
How about adding a parsing flag that would squeeze the error number into e.g. the upper byte of the column number? Not pretty, but would get the job done without breaking ABI compatibility.

**Comment by akheron** [comment]
That's a neat idea. It would not break compatibility because the user's would have to opt-in to changing the meaning of the column field.

The ideal API would be to add macros to read the column number and error code from a `json_error_t`. It would be nice if both worked even if the new parsing flag *wansn't* given, i.e. `column` would always have some indication about whether the flag was used or not.

@phst would you be interested in implementing this and creating a pull request?

**Comment by phst** [comment]
I think it would even be possible to remain fully backwards-compatible without introducing a flag and without bit-twiddling: by setting the second-to-last character in `error.text` to 0 and hiding the error code in the last character.
