### ISSUE TITLE
German mutation ä ü ö and json_string

### ISSUE THREAD

**Issue by SteffKeller** [akheron/jansson#366]
Hello 

I use the precompiled jansson library for ARM cortex provided form ARM/Keil. 
The jansson version is 2.7.

I have to store some strings with german ä,ö und ü in a json string.
But when I try to create an json_string with the function json_t *json_string(const char *value) the creation fails. The  string.type change to JSON_OBJECT and the string.refcount has a large invalid number. 

As I know, jansson should allow this letters, since the are in the Unicode range from U+0000 through U+10FFFF.

I tried json_string_nocheck() but then the fuction json_dumps() fails. 

How can I store this letters  in a json value without any issues?

Thanks a lot, 
BR 
Stefan

**Comment by akheron** [comment]
Could you post a sample code of how you're currently trying to add those letters?

**Comment by SteffKeller** [comment]
Hello akheron

Wow, tanks a lot for your fast response.

Of course here is the code:
`
json_t *jstr1;

	 jstr1 =json_string("Test");
	 jstr1 =json_string("Test ä ö ü");
`
The jstr1 after  add "Test"
![string_test_mutation](https://user-images.githubusercontent.com/32105505/31384278-8dd00b6e-adbe-11e7-8f4b-f022405ac601.png)
The jstr1 after add  "Test ä ö ü"
![string_test](https://user-images.githubusercontent.com/32105505/31384279-8de8553e-adbe-11e7-8603-80c66ff67c6e.png)

BR Stefan

**Comment by akheron** [comment]
I'm not sure how non-ascii characters in C source code are handled by the compiler. It's possible that they are not encoded in UTF-8 but some other encoding.

Using \u00e4 for ä etc. would be the safest way.

**Comment by SteffKeller** [comment]
I contacted the ARM/Keil support with this question, 
I will give you an update about the status. 

BR Stefan

**Comment by SteffKeller** [comment]
Regarding the support form ARM strings from the armcc compiler are normally ISO8859-1 encoded.
As I see in the check in the function utf8_check_first() fails, since the Umlaute ä,ö,ü have the value 0xE4, 0xF6 and 0xFC. 

Is there something to avoid this behaviour or does your library support ISO8859-1?
BR Stefan

**Comment by akheron** [comment]
Jansson only supports UTF-8, but fortunately you have plenty of options :)

1. Use `\u` escapes in your code: Replace ` jstr1 = json_string("Test ä ö ü");` with `jstr1 = json_string("Test  \u00e4 \u00f6 \u00fc");`

2. Instead of in C code, load the data from a UTF-8 encoded file e.g. using `json_loadf`.

3. Use a library to convert your strings from ISO-8859-1 to UTF-8 before passing them to Jansson.

4. If you know the set of non-ASCII characters that are used, you can do the conversion yourself. Replace `"\xe4"` (ISO-8859-1) with `"\xc3\xa4"` (equivalent UTF-8), etc. This involves allocating new strings, because the UTF-8 encoded string is longer than the ISO-8859-1 string, as each non-ASCII character usually takes 2 bytes.

**Comment by danielbruno301** [comment]
Hi @SteffKeller ! Did you use the precompiled jansson library for ARM provided form ARM/Keil on a Cortex M4?
