### ISSUE TITLE
Minimum compiled size

### ISSUE THREAD

**Issue by fotock** [akheron/jansson#386]
The compiled lib file size is more than 80K. It's difficult to use it on small-space Iot boards. 
Is it possible to compile it into a small lib somewhere around 3K ?
Thanks.

**Comment by akheron** [comment]
Hi!

I don't think it's possible to get anywhere near 3K.

I tried compiling with `-s Os` gcc flags, and the `.a` file size was about 86K. I assume this is what you did, too.

Some features can be disabled manually to make the library weigh less, e.g. if you don't need `json_pack()` and `json_unpack()` etc., you can comment out `pack_unpack.c` with `#if 0 / #endif`, or if you don't need `json_dumps()` etc, you can do the same to `dump.c`. Those change dropped the `.a` file size from 59K for me, so you would need to remove virtually all code to get down to 3K.

There are other JSON libraries around, and some of them target embedded system. The list at the bottom of http://json.org lists many C libraries. I clicked on some of them, and at least parson, nxjson, frozen and microjson claim to be lightweight and/or targeted to embedded systems. Maybe you should try one of those instead of Jansson?
