### ISSUE TITLE
Add json_sprintf

### ISSUE THREAD

**Issue by niyamaka** [akheron/jansson#392]
Hi Petri!
I use intensely your great library. There is several sentence that I repeat a lot: convert a number to string and the put it in an object. Something like this:

    char sevent[32];
    snprintf(sevent, sizeof(sevent), "%d", event);
    json_object_set_new(jn_gps_msg, "MessageID", json_string(sevent));

Why not a shortcut like this?:

    json_object_set_new(jn_gps_msg, "MessageID", json_sprintf("%d", event));

being the return of 

    json_t * json_sprintf(const char *format, ...)

 a json string.

Thanks for listening me.
Niyamaka

**Comment by akheron** [comment]
Hi and thanks for the suggestion! I created PR #393, how does it look?

**Comment by niyamaka** [comment]
Thanks to you. 
You will see soon a C framework using your great library in their heart!

**Comment by JamesAllwrightAA** [comment]
I am finding that the json_sprintf() and json_vsprintf() declarations in jansson.h cause problems
because the JANSSON_ATTRS() macro uses variadic arguments, which is a C99 feature. This
causes a build failure for me. I am using Oracle pro*C (a specialized C preprocessor) which
generates an error when it hits these statements. It would be nice if
these functions were conditionally included, perhaps under 
<hash>if defined(__GNUC__) || defined(__clang__) 
<hash>endif
I notice that they only seem to be used in the test suite and not documented as part of the
main library.
