### ISSUE TITLE
Support string with length throughout entire API

### ISSUE THREAD

**Issue by Lexdysic** [akheron/jansson#419]
It looks like as a result of issue #63, some functions accept string with given length like `json_stringn()` and `json_string_setn()`. Unfortunately, not every string parameter has the option to supply a length, like `json_object_get()` and `json_dump_file()`. My codebase uses string-view concept throughout, where a string's length is always known and there is no guarantee of a nul character terminating the string.

Currently, on function calls that do not take a length, I have to copy to a buffer first to ensure there is a nul terminator, then I can pass the copy to the function. Looking at the internals, it looks as though it eventually will call `strlen()` anyway, but for my cases, I can just tell you what the length is.

**Comment by akheron** [comment]
Back then, the multiple requests for this feature all had a shared goal: to carry binary data in JSON strings (i.e. a series of bytes of which some may be nul bytes). That's why string+length is only supported in functions that deal with JSON strings. Furthermore, object keys were exlucded because there's rarely a need to encode non-human-readable data in object keys.

Adding support for string+length *everywhere* would bloat the API considerably, as the current versions of the functions would also need to be kept for backwards compatibility. And anyway, the de-facto representation for strings in C is to terminate them with a nul byte and not store the length explicitly.

**Comment by FooSoft** [comment]
I actually had the same request as well -- we are integrating jansson into our codebase and we too use the concept of a "string view" in order minimize data duplication. We are not interested at all in packing arbitrary data into dictionary keys but rather being able to use "views" into already-allocated buffers without having to modify them. For example, imagine a version of `strtok` that does not have to modify the input string and instead simply outputs pointers and lengths for the parsed tokens.

I understand the concern about API bloat, but this is actually a pattern that is growing in popularity (with out of the box support in C++, see http://en.cppreference.com/w/cpp/string/basic_string_view). I hope you reconsider this issue as while it would increase the size of the API, it would not make it any more difficult to understand. If anything, it would make it more consistant as "string view" is essentially half-supported already.
