### ISSUE TITLE
"invalid escape" from "json_loads"

### ISSUE THREAD

**Issue by Jexbat** [akheron/jansson#450]
`json_loads` load some user input with slash character in Chinese ,like "抗冲击\聚丙烯" and cause `invalid escape`，how to aviod this error. I konw there is `JSON_ESCAPE_SLASH` flag to encoding json, but how to decode some json with '\'.

**Comment by ploxiln** [comment]
In json strings, back-slash `\` is always special. `JSON_EXCAPE_SLASH` is for escaping forward-slash `/` with a back-slash, resulting in `\/` - I think this is a historical oddity, and it is logically not really necessary, which is why it is optional. Some non-printing characters always need back-slash escaping, like a newline: `\n`. For an actual back-slash to be included in the string value and not be confused with a special escaped character, it must be escaped with another back-slash, e.g `\\`, by the encoder of the json.

**Comment by coreyfarrell** [comment]
@ploxiln is correct, the backslash has special meaning in JSON strings.  See http://json.org/ for a good overview of the JSON format.  Specifically `\`, `"` and control characters must be escaped.
